bacs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("bacsApp.urls")),
    path("admin/", admin.site.urls),
]

bacsApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("formulaire", views.formulaire, name="formulaire"),
    path("login", views.login, name="login"),
    path("logout",views.logout, name="logout"),
    path("liste",views.liste, name="liste")
]

bacsApp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Utilisateur(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    nom = models.CharField(max_length=30,null=True)
    mdp = models.CharField(max_length=30,null=True)

    def __str__(self):
        return self.nom
    

class Bac(models.Model):
    libelle = models.CharField(max_length=30)
    objects = models.Manager()
    
    def __str__(self):
        return self.libelle

class Site(models.Model):
    adresse = models.CharField(max_length=30,null=True)
    bac = models.ManyToManyField(Bac,through="Stock")
    objects = models.Manager()

    def __str__(self):
        return self.adresse

class Document(models.Model):
    url = models.FileField(upload_to="",null=True)
    objects = models.Manager()

    def __str__(self):
        return self.url

class Livraison(models.Model):
    site = models.ForeignKey(Site, on_delete = models.SET_NULL, null= True)
    date = models.CharField(max_length=30)
    retour = models.CharField(max_length=30,default=False)
    utilisateur = models.ForeignKey(Utilisateur, on_delete = models.SET_NULL, null= True)
    une_cargaison = models.ManyToManyField(Bac,through="Cargaison")
    document = models.ManyToManyField(Document)
    objects = models.Manager()

class Cargaison(models.Model):
    bac = models.ForeignKey(Bac,on_delete=models.SET_NULL, null=True)
    livraison = models.ForeignKey(Livraison,on_delete=models.SET_NULL, null=True)
    quantite = models.PositiveIntegerField()
    objects = models.Manager()
    
    def __str__(self):
        return self.quantite


class Stock(models.Model):
    quantite = models.PositiveIntegerField(default=0)
    site = models.ForeignKey(Site,on_delete=models.SET_NULL, null=True)
    bac = models.ForeignKey(Bac,on_delete=models.SET_NULL, null=True)
    objects = models.Manager()

bacsApp/views.py
from django.http import HttpResponse
from django.contrib.auth import authenticate, login as auth_login,logout as auth_logout
from django.template import loader
from django.shortcuts import render, redirect
from .models import *
from django.shortcuts import redirect

def index(request):
    return render(request,"index.html")


def formulaire(request):
    bacs = Bac.objects.all()
    if request.method == 'POST':
        print(request.POST)
        site = Site.objects.get_or_create(adresse = request.POST["adresse"])
        retour = request.POST.get('retour',False)
        user = Utilisateur.objects.filter(user = request.user)
        livraison = Livraison.objects.create(site=site[0],
                              date=request.POST["dateLiv"],
                              retour=retour,
                              utilisateur = user[0])
        for document in request.FILES.getlist('fichier'):
            doc = Document.objects.create(url = document)
            livraison.document.add(doc)    
        stock1 = Stock.objects.get_or_create(site = site[0],bac=bacs[0])
        stock2 = Stock.objects.get_or_create(site = site[0],bac=bacs[1])
        fournisseur = Site.objects.get(id = 1)
        stockFournB1 = Stock.objects.get(site = fournisseur, bac=bacs[0])
        stockFournB2 = Stock.objects.get(site = fournisseur, bac=bacs[1])
        Cargaison.objects.create(livraison = livraison,bac = bacs[0],quantite = int(request.POST["Bac1"]))
        Cargaison.objects.create(livraison = livraison,bac = bacs[1],quantite = int(request.POST["Bac2"]))
        if retour == "on":
            stockFournB1.quantite = stockFournB1.quantite + int(request.POST["Bac1"])
            stockFournB1.save()
            stockFournB2.quantite = stockFournB2.quantite + int(request.POST["Bac2"])
            stockFournB2.save() 
            if stock1[0].quantite != 0: 
                stock1[0].quantite -= int(request.POST["Bac1"])
                stock1[0].save()
            if stock2[0].quantite != 0: 
                stock2[0].quantite -= int(request.POST["Bac2"])
                stock2[0].save()
        else:
            stockFournB1.quantite = stockFournB1.quantite - int(request.POST["Bac1"])
            stockFournB1.save()
            stockFournB2.quantite = stockFournB2.quantite - int(request.POST["Bac2"])
            stockFournB2.save() 
            stock1[0].quantite += int(request.POST["Bac1"])
            stock1[0].save()
            stock2[0].quantite += int(request.POST["Bac2"])
            stock2[0].save()
    return render(request,"formulaire.html",{"bacs": bacs})

def login(request):
    if request.method == 'POST' :
        user = authenticate(request,username=request.POST["nom"], password=request.POST["mdp"])
        if user is not None:
            print(user)
            auth_login(request,user)
            return redirect("/")

    return render(request,"login.html")

def logout(request):
    auth_logout(request)
    return redirect("/")


def liste(request):
    user = request.user
    if(user.is_anonymous):
        print(request.user)
        return redirect("/login")
    else:
        if user.groups.filter(name='Responsables').exists(): 
            livraisons = Livraison.objects.all()
            for object in livraisons:
                object = object.cargaison_set.all()
                for a in object:
                    print(a.quantite)

        else:
            livraisons = Livraison.objects.filter(utilisateur=user)            
    return render(request,"liste.html",{"livraisons":livraisons})

bacsApp/templates/base.html
{% block header %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
{% endblock %}

{% block body %}


{% endblock %}

{% block footer %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</html>
{% endblock %} 

bacsApp/templates/formulaire.html
{% extends "base.html" %}

{% block body %}
{% include "header.html" %}
<h1 style="display: flex;justify-content: center;padding-top:3%">Formulaire de livraison</h1>
<div class="container" style="max-width:30%">
  <div class = "col">
    <div class = "row ">
      <div class ="form ">
        <form method="POST" action="/formulaire" enctype='multipart/form-data'>
          {% csrf_token %}
          <div class="wrapper" style="padding-top: 3%;">
            <label for="dateLiv">Date de la livraison</label>
            <input type="date" class="form-control" name="dateLiv" id="formChauff" placeholder="Saisisez la date" required>
          </div>
          <div class="wrapper"style="padding-top: 3%;">
            <label class="form-check-label" for="retour">Retour?</label>
            <input type="checkbox" class="form-check-input" name="retour" id="Retour">
          </div>
          <div class="row"style="padding-top: 3%;">
            <label class="form-check-label" for="fichier">Choisir un fichier</label>
          </div>
          <div class="row"id="fichier-wrp" style="padding-top: 3%;padding-bottom: 3%;">
            <input type="file" class="ajouterFichier" name="fichier" id="fichier" style="width: 100px;height:30px">
          </div>
          <div class="autre-fichier-wrp"style="padding-top: 3%;">
            <button type="button" class="btn btn-secondary" id="fichier-button" >Ajouter d'autres fichiers</button>
          </div>
          <div class="row"style="padding-top:3%" >
            <label>Cargaison de bacs</label>
          </div>
          <div class="row" id="bac" style="padding: 3%;border:1px solid black">
            <label for="inputNumber1" style="padding-top: 3%;">Bac1</label>
            <input type="number" class="form-control" id="inputNumber1" name="Bac1" placeholder="Numéro de bacs" min="0" value="0">
          </div>
          <div class="row" id="bac" style="padding: 3%;border:1px solid black">
            <label for="inputNumber2" style="padding-top: 3%;">Bac2</label>
            <input type="number" class="form-control" id="inputNumber2" name="Bac2" placeholder="Numéro de bacs" min="0" value="0">
          </div>
          <div class="adresse"style="padding-top: 3%;">
            <label class="form-check-label" for="adresse">Saisisez l'adresse de livraison</label>
            <input type="text" class="form-control" name="adresse" placeholder="Saisisez l'adresse de livraison">
          </div>
          <div class="submit" style=" padding-top: 5%;">
            <button type="submit" class="btn btn-primary" >Envoyer</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
  {% endblock %}
  {% block footer %}
  
  <script>
    divButton = document.getElementById("fichier-button").addEventListener("click",function cloneDiv (){
      divFichier = document.getElementById("fichier-wrp")
      divInput = document.getElementById("fichier")
      divInput2 = divInput.cloneNode(true);
      divInput2.setAttribute("id", divInput2.id+1)
      divFichier.appendChild(divInput2)
    });
  </script>
    {% endblock %}
  

bacsApp/templates/header.html
{% block head %}
<div>
    {% load static %}
    <div class="container">
        <div class="row" style="padding-top: 2%;padding-left: 2%;display: flex;">
            <div class="col">
                <a href="/" ><img src="{% static 'sp_home_logo.png' %}" class="img-fluid border rounded-3 mb-4" alt="Example image" loading="lazy" width="200px" height="200px"></a>
            </div>
            <div class="col" style="min-width:70%">
            </div>
            {% if user.is_authenticated %}
            <div class="col">
                <a href="/logout"> <button type="button" class="btn btn-primary" style="min-height: 60px; min-width: 60px;">Déconnection</button> </a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

bacsApp/templates/index.html
{% extends 'base.html' %}

{% block body %}
<body style ="min-height: 90%">
    <div class="px-4 pt-5 my-5 text-center border-bottom" >
      <div class="overflow-hidden" style="min-height: 60vh;">
        <div class="container px-5">
          {% load static %}
          <img src="{% static 'supergel_logo.png' %}" class="img-fluid border rounded-3 mb-4" alt="Example image" loading="lazy" width="700" height="500">
        </div>
        {% if user.is_authenticated %}
        <a href="/logout"> <button type="button" class="btn btn-primary" style="min-height: 60px; min-width: 60px;">Se déconnecter</button> </a>
          {% if perms.bacsApp.change_stock %}
          <a href="/liste"><button type="button" class="btn btn-info" style="min-height: 60px; min-width: 60px;">Liste des livraisons</button></a>  
          {% endif %}

        <a href="/formulaire"><button type="button" class="btn btn-warning" style="min-height: 60px; min-width: 60px;">Ajouter une livraison</button></a>
        <a href="#"><button type="button" class="btn btn-success" style="min-height: 60px; min-width: 60px;">Statistiques</button></a>
        {# <h1>{{perms.app_name}}</h1> #}
        {% else %}
        <a href="/login"> <button type="button" class="btn btn-primary" style="min-height: 60px; min-width: 60px;">Se connecter</button> </a>
        {% endif %}
      </div>
    </div>
</body>
{% endblock %}

bacsApp/templates/liste.html
{% extends "base.html" %}
{% block body %}
{% include "header.html" %}
    <div class="row" style="display:flexbox;padding-left:5%;padding-right:6%;">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Destinataire</th>
                <th scope="col">Chauffeur</th>
                <th scope="col">Quantité Bac type 1</th>
                <th scope="col">Quantité Bac type 2</th>
            </tr>
            </thead>
            
        {% for livraison in livraisons %}
            <tbody>
                <tr>
                    <td>{{livraison.date}}</td>
                    <td>{{livraison.site}}</td>
                    <td>{{livraison.utilisateur}}</td>
                {% for cargaison in livraison.cargaison_set.all %}
                    <td>{{cargaison.quantite}}</td>
                {% endfor %}
                    <td><a href="#"><button type="button" class="btn btn-warning btn-sm">Editer</button></a></td>
                    <td><a href="#"><button type="button" class="btn btn-danger btn-sm">Effacer</button></a></td>
                </tr>
        {% endfor %}
        </table>
    </div>
{% endblock %}

bacsApp/templates/login.html
{% extends "base.html" %}

{% block body %}
{% include "header.html" %}
    <div class="row" style="padding: 10%;">
        <h1 style="padding-left: 43%;padding-bottom:5%;">Connection</h1>
        <form action="/login" method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            
            <div class="form-outline mb-4">
            <label class="form-label" id="nom" for="nom">Mon d'utilisateur</label>
            <input type="text" name="nom" class="form-control" />
            </div>
            
            <div class="form-outline mb-4">
            <label class="form-label" id="mdp" for="mdp">Mot de passe</label>
            <input type="password" name="mdp" id="mdp" class="form-control" />
            </div>
        
           
            <div class="row mb-4">
                <div class="col d-flex justify-content-center">
                  
                    <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
                    <label class="form-check-label" for="form2Example31"> Se souvenir de moi </label>
                    </div>
                </div>
        
                <div class="col">
                    
                    <a href="#!">Mot de passe oubliée?</a>
                </div>
            </div>
        
           
            <input type="submit" class="btn btn-primary btn-block mb-4" value="Se Connecter"></input>

            </div>
        </form>
    </div>

{% endblock %}